//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiosInstitucionales.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_BA_Aplicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PI_BA_Aplicacion()
        {
            this.PI_BA_Respuesta = new HashSet<PI_BA_Respuesta>();
            this.PI_BA_Evaluacion = new HashSet<PI_BA_Evaluacion>();
            this.PI_BA_Categoria1 = new HashSet<PI_BA_Categoria>();
        }
    
        public string cveAplicacion { get; set; }
        public string Status { get; set; }
        public string cveCandidato { get; set; }
        public string cveCategoria { get; set; }
    
        public virtual PI_BA_Candidato PI_BA_Candidato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PI_BA_Respuesta> PI_BA_Respuesta { get; set; }
        public virtual PI_BA_Categoria PI_BA_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PI_BA_Evaluacion> PI_BA_Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PI_BA_Categoria> PI_BA_Categoria1 { get; set; }
    }
}
