//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiosInstitucionales.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_BA_Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PI_BA_Pregunta()
        {
            this.PI_BA_PreguntasPorForma = new HashSet<PI_BA_PreguntasPorForma>();
            this.PI_BA_Respuesta = new HashSet<PI_BA_Respuesta>();
        }
    
        public string cvePregunta { get; set; }
        public string Texto { get; set; }
        public string IdentificadorObjeto { get; set; }
        public string TipoCampo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PI_BA_PreguntasPorForma> PI_BA_PreguntasPorForma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PI_BA_Respuesta> PI_BA_Respuesta { get; set; }
    }
}
