//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiosInstitucionales.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_BA_PreguntasPorForma
    {
        public string cvePreguntaPorForma { get; set; }
        public string cveForma { get; set; }
        public string cvePregunta { get; set; }
    
        public virtual PI_BA_Forma PI_BA_Forma { get; set; }
        public virtual PI_BA_Pregunta PI_BA_Pregunta { get; set; }
    }
}
