//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiosInstitucionales.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_SE_Configuracion
    {
        public string cveConfiguracion { get; set; }
        public string Correo { get; set; }
        public string Password { get; set; }
        public string Host { get; set; }
        public Nullable<short> Puerto { get; set; }
    }
}
