//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiosInstitucionales.Entities.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class wPremiosInstitucionalesdbEntities : DbContext
    {
        public wPremiosInstitucionalesdbEntities()
            : base("name=wPremiosInstitucionalesdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PI_BA_Aplicacion> PI_BA_Aplicacion { get; set; }
        public virtual DbSet<PI_BA_Candidato> PI_BA_Candidato { get; set; }
        public virtual DbSet<PI_BA_Categoria> PI_BA_Categoria { get; set; }
        public virtual DbSet<PI_BA_Convocatoria> PI_BA_Convocatoria { get; set; }
        public virtual DbSet<PI_BA_Evaluacion> PI_BA_Evaluacion { get; set; }
        public virtual DbSet<PI_BA_Forma> PI_BA_Forma { get; set; }
        public virtual DbSet<PI_BA_Juez> PI_BA_Juez { get; set; }
        public virtual DbSet<PI_BA_JuezPorCategoria> PI_BA_JuezPorCategoria { get; set; }
        public virtual DbSet<PI_BA_Pregunta> PI_BA_Pregunta { get; set; }
        public virtual DbSet<PI_BA_PreguntasPorForma> PI_BA_PreguntasPorForma { get; set; }
        public virtual DbSet<PI_BA_Premio> PI_BA_Premio { get; set; }
        public virtual DbSet<PI_BA_Respuesta> PI_BA_Respuesta { get; set; }
        public virtual DbSet<PI_SE_Administrador> PI_SE_Administrador { get; set; }
        public virtual DbSet<PI_SE_Configuracion> PI_SE_Configuracion { get; set; }
    
        public virtual int AddCandidato(string cveCandidato, string password, string nombre, string apellido, Nullable<bool> confirmado, string correo, string codigoConfirmacion, string telefono, string nacionalidad, string rFC, string direccion, string nombreImagen, Nullable<System.DateTime> fechaPrivacidadDatos)
        {
            var cveCandidatoParameter = cveCandidato != null ?
                new ObjectParameter("cveCandidato", cveCandidato) :
                new ObjectParameter("cveCandidato", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var confirmadoParameter = confirmado.HasValue ?
                new ObjectParameter("Confirmado", confirmado) :
                new ObjectParameter("Confirmado", typeof(bool));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var codigoConfirmacionParameter = codigoConfirmacion != null ?
                new ObjectParameter("CodigoConfirmacion", codigoConfirmacion) :
                new ObjectParameter("CodigoConfirmacion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var nacionalidadParameter = nacionalidad != null ?
                new ObjectParameter("Nacionalidad", nacionalidad) :
                new ObjectParameter("Nacionalidad", typeof(string));
    
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var nombreImagenParameter = nombreImagen != null ?
                new ObjectParameter("NombreImagen", nombreImagen) :
                new ObjectParameter("NombreImagen", typeof(string));
    
            var fechaPrivacidadDatosParameter = fechaPrivacidadDatos.HasValue ?
                new ObjectParameter("FechaPrivacidadDatos", fechaPrivacidadDatos) :
                new ObjectParameter("FechaPrivacidadDatos", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCandidato", cveCandidatoParameter, passwordParameter, nombreParameter, apellidoParameter, confirmadoParameter, correoParameter, codigoConfirmacionParameter, telefonoParameter, nacionalidadParameter, rFCParameter, direccionParameter, nombreImagenParameter, fechaPrivacidadDatosParameter);
        }
    
        public virtual int AddCategoria(string cveCategoria, string nombre, string cveConvocatoria, string cveAplicacionGanadora, Nullable<System.DateTime> fechaCreacion, string usuarioCreacion, Nullable<System.DateTime> fechaEdicion, string usuarioEdicion)
        {
            var cveCategoriaParameter = cveCategoria != null ?
                new ObjectParameter("cveCategoria", cveCategoria) :
                new ObjectParameter("cveCategoria", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var cveConvocatoriaParameter = cveConvocatoria != null ?
                new ObjectParameter("cveConvocatoria", cveConvocatoria) :
                new ObjectParameter("cveConvocatoria", typeof(string));
    
            var cveAplicacionGanadoraParameter = cveAplicacionGanadora != null ?
                new ObjectParameter("cveAplicacionGanadora", cveAplicacionGanadora) :
                new ObjectParameter("cveAplicacionGanadora", typeof(string));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            var fechaEdicionParameter = fechaEdicion.HasValue ?
                new ObjectParameter("FechaEdicion", fechaEdicion) :
                new ObjectParameter("FechaEdicion", typeof(System.DateTime));
    
            var usuarioEdicionParameter = usuarioEdicion != null ?
                new ObjectParameter("UsuarioEdicion", usuarioEdicion) :
                new ObjectParameter("UsuarioEdicion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCategoria", cveCategoriaParameter, nombreParameter, cveConvocatoriaParameter, cveAplicacionGanadoraParameter, fechaCreacionParameter, usuarioCreacionParameter, fechaEdicionParameter, usuarioEdicionParameter);
        }
    
        public virtual int AddConvocatoria(string cveConvocatoria, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string cvePremio, string tituloConvocatoria, Nullable<System.DateTime> fechaVeredicto, Nullable<System.DateTime> fechaCreacion, string usuarioCreacion, Nullable<System.DateTime> fechaEdicion, string usuarioEdicion)
        {
            var cveConvocatoriaParameter = cveConvocatoria != null ?
                new ObjectParameter("cveConvocatoria", cveConvocatoria) :
                new ObjectParameter("cveConvocatoria", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var cvePremioParameter = cvePremio != null ?
                new ObjectParameter("cvePremio", cvePremio) :
                new ObjectParameter("cvePremio", typeof(string));
    
            var tituloConvocatoriaParameter = tituloConvocatoria != null ?
                new ObjectParameter("TituloConvocatoria", tituloConvocatoria) :
                new ObjectParameter("TituloConvocatoria", typeof(string));
    
            var fechaVeredictoParameter = fechaVeredicto.HasValue ?
                new ObjectParameter("FechaVeredicto", fechaVeredicto) :
                new ObjectParameter("FechaVeredicto", typeof(System.DateTime));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            var fechaEdicionParameter = fechaEdicion.HasValue ?
                new ObjectParameter("FechaEdicion", fechaEdicion) :
                new ObjectParameter("FechaEdicion", typeof(System.DateTime));
    
            var usuarioEdicionParameter = usuarioEdicion != null ?
                new ObjectParameter("UsuarioEdicion", usuarioEdicion) :
                new ObjectParameter("UsuarioEdicion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddConvocatoria", cveConvocatoriaParameter, fechaInicioParameter, fechaFinParameter, cvePremioParameter, tituloConvocatoriaParameter, fechaVeredictoParameter, fechaCreacionParameter, usuarioCreacionParameter, fechaEdicionParameter, usuarioEdicionParameter);
        }
    
        public virtual int AddEvaluacion(string cveEvaluacion, Nullable<short> calificacion, string cveAplicacion, string cveJuez)
        {
            var cveEvaluacionParameter = cveEvaluacion != null ?
                new ObjectParameter("cveEvaluacion", cveEvaluacion) :
                new ObjectParameter("cveEvaluacion", typeof(string));
    
            var calificacionParameter = calificacion.HasValue ?
                new ObjectParameter("Calificacion", calificacion) :
                new ObjectParameter("Calificacion", typeof(short));
    
            var cveAplicacionParameter = cveAplicacion != null ?
                new ObjectParameter("cveAplicacion", cveAplicacion) :
                new ObjectParameter("cveAplicacion", typeof(string));
    
            var cveJuezParameter = cveJuez != null ?
                new ObjectParameter("cveJuez", cveJuez) :
                new ObjectParameter("cveJuez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddEvaluacion", cveEvaluacionParameter, calificacionParameter, cveAplicacionParameter, cveJuezParameter);
        }
    
        public virtual int AddForma(string cveForma, string cveCategoria, Nullable<System.DateTime> fechaCreacion, string usuarioCreacion, Nullable<System.DateTime> fechaEdicion, string usuarioEdicion)
        {
            var cveFormaParameter = cveForma != null ?
                new ObjectParameter("cveForma", cveForma) :
                new ObjectParameter("cveForma", typeof(string));
    
            var cveCategoriaParameter = cveCategoria != null ?
                new ObjectParameter("cveCategoria", cveCategoria) :
                new ObjectParameter("cveCategoria", typeof(string));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            var fechaEdicionParameter = fechaEdicion.HasValue ?
                new ObjectParameter("FechaEdicion", fechaEdicion) :
                new ObjectParameter("FechaEdicion", typeof(System.DateTime));
    
            var usuarioEdicionParameter = usuarioEdicion != null ?
                new ObjectParameter("UsuarioEdicion", usuarioEdicion) :
                new ObjectParameter("UsuarioEdicion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddForma", cveFormaParameter, cveCategoriaParameter, fechaCreacionParameter, usuarioCreacionParameter, fechaEdicionParameter, usuarioEdicionParameter);
        }
    
        public virtual int AddJuez(string cveJuez, string password, string nombre, string apellido, string correo, string nombreImagen)
        {
            var cveJuezParameter = cveJuez != null ?
                new ObjectParameter("cveJuez", cveJuez) :
                new ObjectParameter("cveJuez", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var nombreImagenParameter = nombreImagen != null ?
                new ObjectParameter("NombreImagen", nombreImagen) :
                new ObjectParameter("NombreImagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddJuez", cveJuezParameter, passwordParameter, nombreParameter, apellidoParameter, correoParameter, nombreImagenParameter);
        }
    
        public virtual int AddPremio(string cvePremio, string nombre, string nombreImagen, string descripcion, Nullable<System.DateTime> fechaCreacion, string usuarioCreacion, Nullable<System.DateTime> fechaEdicion, string usuarioEdicion)
        {
            var cvePremioParameter = cvePremio != null ?
                new ObjectParameter("cvePremio", cvePremio) :
                new ObjectParameter("cvePremio", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var nombreImagenParameter = nombreImagen != null ?
                new ObjectParameter("NombreImagen", nombreImagen) :
                new ObjectParameter("NombreImagen", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            var fechaEdicionParameter = fechaEdicion.HasValue ?
                new ObjectParameter("FechaEdicion", fechaEdicion) :
                new ObjectParameter("FechaEdicion", typeof(System.DateTime));
    
            var usuarioEdicionParameter = usuarioEdicion != null ?
                new ObjectParameter("UsuarioEdicion", usuarioEdicion) :
                new ObjectParameter("UsuarioEdicion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPremio", cvePremioParameter, nombreParameter, nombreImagenParameter, descripcionParameter, fechaCreacionParameter, usuarioCreacionParameter, fechaEdicionParameter, usuarioEdicionParameter);
        }
    
        public virtual int ConfirmarCandidato(string codigoConfirmacion)
        {
            var codigoConfirmacionParameter = codigoConfirmacion != null ?
                new ObjectParameter("CodigoConfirmacion", codigoConfirmacion) :
                new ObjectParameter("CodigoConfirmacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConfirmarCandidato", codigoConfirmacionParameter);
        }
    
        public virtual ObjectResult<PI_SE_Administrador> GetAdministrador(string correo, string cveAdministrador)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var cveAdministradorParameter = cveAdministrador != null ?
                new ObjectParameter("cveAdministrador", cveAdministrador) :
                new ObjectParameter("cveAdministrador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_SE_Administrador>("GetAdministrador", correoParameter, cveAdministradorParameter);
        }
    
        public virtual ObjectResult<PI_SE_Administrador> GetAdministrador(string correo, string cveAdministrador, MergeOption mergeOption)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var cveAdministradorParameter = cveAdministrador != null ?
                new ObjectParameter("cveAdministrador", cveAdministrador) :
                new ObjectParameter("cveAdministrador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_SE_Administrador>("GetAdministrador", mergeOption, correoParameter, cveAdministradorParameter);
        }
    
        public virtual ObjectResult<PI_BA_Candidato> GetCandidato(string correo, string cveCandidato)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var cveCandidatoParameter = cveCandidato != null ?
                new ObjectParameter("cveCandidato", cveCandidato) :
                new ObjectParameter("cveCandidato", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Candidato>("GetCandidato", correoParameter, cveCandidatoParameter);
        }
    
        public virtual ObjectResult<PI_BA_Candidato> GetCandidato(string correo, string cveCandidato, MergeOption mergeOption)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var cveCandidatoParameter = cveCandidato != null ?
                new ObjectParameter("cveCandidato", cveCandidato) :
                new ObjectParameter("cveCandidato", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Candidato>("GetCandidato", mergeOption, correoParameter, cveCandidatoParameter);
        }
    
        public virtual ObjectResult<PI_BA_Categoria> GetCategoria(string cveCategoria, string cveConvocatoria)
        {
            var cveCategoriaParameter = cveCategoria != null ?
                new ObjectParameter("cveCategoria", cveCategoria) :
                new ObjectParameter("cveCategoria", typeof(string));
    
            var cveConvocatoriaParameter = cveConvocatoria != null ?
                new ObjectParameter("cveConvocatoria", cveConvocatoria) :
                new ObjectParameter("cveConvocatoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Categoria>("GetCategoria", cveCategoriaParameter, cveConvocatoriaParameter);
        }
    
        public virtual ObjectResult<PI_BA_Categoria> GetCategoria(string cveCategoria, string cveConvocatoria, MergeOption mergeOption)
        {
            var cveCategoriaParameter = cveCategoria != null ?
                new ObjectParameter("cveCategoria", cveCategoria) :
                new ObjectParameter("cveCategoria", typeof(string));
    
            var cveConvocatoriaParameter = cveConvocatoria != null ?
                new ObjectParameter("cveConvocatoria", cveConvocatoria) :
                new ObjectParameter("cveConvocatoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Categoria>("GetCategoria", mergeOption, cveCategoriaParameter, cveConvocatoriaParameter);
        }
    
        public virtual ObjectResult<PI_BA_Categoria> GetCategoriaByIdJuez(string cveJuez)
        {
            var cveJuezParameter = cveJuez != null ?
                new ObjectParameter("cveJuez", cveJuez) :
                new ObjectParameter("cveJuez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Categoria>("GetCategoriaByIdJuez", cveJuezParameter);
        }
    
        public virtual ObjectResult<PI_BA_Categoria> GetCategoriaByIdJuez(string cveJuez, MergeOption mergeOption)
        {
            var cveJuezParameter = cveJuez != null ?
                new ObjectParameter("cveJuez", cveJuez) :
                new ObjectParameter("cveJuez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Categoria>("GetCategoriaByIdJuez", mergeOption, cveJuezParameter);
        }
    
        public virtual ObjectResult<PI_BA_Categoria> GetCategoriasPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Categoria>("GetCategoriasPendientes");
        }
    
        public virtual ObjectResult<PI_BA_Categoria> GetCategoriasPendientes(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Categoria>("GetCategoriasPendientes", mergeOption);
        }
    
        public virtual ObjectResult<PI_BA_Convocatoria> GetConvocatoria(string cveConvocatoria)
        {
            var cveConvocatoriaParameter = cveConvocatoria != null ?
                new ObjectParameter("cveConvocatoria", cveConvocatoria) :
                new ObjectParameter("cveConvocatoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Convocatoria>("GetConvocatoria", cveConvocatoriaParameter);
        }
    
        public virtual ObjectResult<PI_BA_Convocatoria> GetConvocatoria(string cveConvocatoria, MergeOption mergeOption)
        {
            var cveConvocatoriaParameter = cveConvocatoria != null ?
                new ObjectParameter("cveConvocatoria", cveConvocatoria) :
                new ObjectParameter("cveConvocatoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Convocatoria>("GetConvocatoria", mergeOption, cveConvocatoriaParameter);
        }
    
        public virtual ObjectResult<PI_BA_Evaluacion> GetEvaluacion(string cveEvaluacion, string cveAplicacion, string cveJuez)
        {
            var cveEvaluacionParameter = cveEvaluacion != null ?
                new ObjectParameter("cveEvaluacion", cveEvaluacion) :
                new ObjectParameter("cveEvaluacion", typeof(string));
    
            var cveAplicacionParameter = cveAplicacion != null ?
                new ObjectParameter("cveAplicacion", cveAplicacion) :
                new ObjectParameter("cveAplicacion", typeof(string));
    
            var cveJuezParameter = cveJuez != null ?
                new ObjectParameter("cveJuez", cveJuez) :
                new ObjectParameter("cveJuez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Evaluacion>("GetEvaluacion", cveEvaluacionParameter, cveAplicacionParameter, cveJuezParameter);
        }
    
        public virtual ObjectResult<PI_BA_Evaluacion> GetEvaluacion(string cveEvaluacion, string cveAplicacion, string cveJuez, MergeOption mergeOption)
        {
            var cveEvaluacionParameter = cveEvaluacion != null ?
                new ObjectParameter("cveEvaluacion", cveEvaluacion) :
                new ObjectParameter("cveEvaluacion", typeof(string));
    
            var cveAplicacionParameter = cveAplicacion != null ?
                new ObjectParameter("cveAplicacion", cveAplicacion) :
                new ObjectParameter("cveAplicacion", typeof(string));
    
            var cveJuezParameter = cveJuez != null ?
                new ObjectParameter("cveJuez", cveJuez) :
                new ObjectParameter("cveJuez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Evaluacion>("GetEvaluacion", mergeOption, cveEvaluacionParameter, cveAplicacionParameter, cveJuezParameter);
        }
    
        public virtual ObjectResult<PI_BA_Forma> GetForma(string cveForma)
        {
            var cveFormaParameter = cveForma != null ?
                new ObjectParameter("cveForma", cveForma) :
                new ObjectParameter("cveForma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Forma>("GetForma", cveFormaParameter);
        }
    
        public virtual ObjectResult<PI_BA_Forma> GetForma(string cveForma, MergeOption mergeOption)
        {
            var cveFormaParameter = cveForma != null ?
                new ObjectParameter("cveForma", cveForma) :
                new ObjectParameter("cveForma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Forma>("GetForma", mergeOption, cveFormaParameter);
        }
    
        public virtual ObjectResult<PI_BA_Juez> GetJuez(string correo, string cveJuez)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var cveJuezParameter = cveJuez != null ?
                new ObjectParameter("cveJuez", cveJuez) :
                new ObjectParameter("cveJuez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Juez>("GetJuez", correoParameter, cveJuezParameter);
        }
    
        public virtual ObjectResult<PI_BA_Juez> GetJuez(string correo, string cveJuez, MergeOption mergeOption)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var cveJuezParameter = cveJuez != null ?
                new ObjectParameter("cveJuez", cveJuez) :
                new ObjectParameter("cveJuez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Juez>("GetJuez", mergeOption, correoParameter, cveJuezParameter);
        }
    
        public virtual ObjectResult<PI_BA_Convocatoria> GetMostRecentConvocatoria(string cvePremio)
        {
            var cvePremioParameter = cvePremio != null ?
                new ObjectParameter("cvePremio", cvePremio) :
                new ObjectParameter("cvePremio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Convocatoria>("GetMostRecentConvocatoria", cvePremioParameter);
        }
    
        public virtual ObjectResult<PI_BA_Convocatoria> GetMostRecentConvocatoria(string cvePremio, MergeOption mergeOption)
        {
            var cvePremioParameter = cvePremio != null ?
                new ObjectParameter("cvePremio", cvePremio) :
                new ObjectParameter("cvePremio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Convocatoria>("GetMostRecentConvocatoria", mergeOption, cvePremioParameter);
        }
    
        public virtual ObjectResult<PI_BA_Premio> GetPremio(string cvePremio)
        {
            var cvePremioParameter = cvePremio != null ?
                new ObjectParameter("cvePremio", cvePremio) :
                new ObjectParameter("cvePremio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Premio>("GetPremio", cvePremioParameter);
        }
    
        public virtual ObjectResult<PI_BA_Premio> GetPremio(string cvePremio, MergeOption mergeOption)
        {
            var cvePremioParameter = cvePremio != null ?
                new ObjectParameter("cvePremio", cvePremio) :
                new ObjectParameter("cvePremio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Premio>("GetPremio", mergeOption, cvePremioParameter);
        }
    
        public virtual ObjectResult<PI_BA_Premio> GetPremioByIdCategoria(string cveCategoria)
        {
            var cveCategoriaParameter = cveCategoria != null ?
                new ObjectParameter("cveCategoria", cveCategoria) :
                new ObjectParameter("cveCategoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Premio>("GetPremioByIdCategoria", cveCategoriaParameter);
        }
    
        public virtual ObjectResult<PI_BA_Premio> GetPremioByIdCategoria(string cveCategoria, MergeOption mergeOption)
        {
            var cveCategoriaParameter = cveCategoria != null ?
                new ObjectParameter("cveCategoria", cveCategoria) :
                new ObjectParameter("cveCategoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_BA_Premio>("GetPremioByIdCategoria", mergeOption, cveCategoriaParameter);
        }
    
        public virtual int UpdateAdministrador(string cveAdministrador, string password, string correo)
        {
            var cveAdministradorParameter = cveAdministrador != null ?
                new ObjectParameter("cveAdministrador", cveAdministrador) :
                new ObjectParameter("cveAdministrador", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAdministrador", cveAdministradorParameter, passwordParameter, correoParameter);
        }
    
        public virtual int UpdateCandidato(string cveCandidato, string password, string nombre, string apellido, Nullable<bool> confirmado, string correo, string codigoConfirmacion, string telefono, string nacionalidad, string rFC, string direccion, string nombreImagen, Nullable<System.DateTime> fechaPrivacidadDatos)
        {
            var cveCandidatoParameter = cveCandidato != null ?
                new ObjectParameter("cveCandidato", cveCandidato) :
                new ObjectParameter("cveCandidato", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var confirmadoParameter = confirmado.HasValue ?
                new ObjectParameter("Confirmado", confirmado) :
                new ObjectParameter("Confirmado", typeof(bool));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var codigoConfirmacionParameter = codigoConfirmacion != null ?
                new ObjectParameter("CodigoConfirmacion", codigoConfirmacion) :
                new ObjectParameter("CodigoConfirmacion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var nacionalidadParameter = nacionalidad != null ?
                new ObjectParameter("Nacionalidad", nacionalidad) :
                new ObjectParameter("Nacionalidad", typeof(string));
    
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var nombreImagenParameter = nombreImagen != null ?
                new ObjectParameter("NombreImagen", nombreImagen) :
                new ObjectParameter("NombreImagen", typeof(string));
    
            var fechaPrivacidadDatosParameter = fechaPrivacidadDatos.HasValue ?
                new ObjectParameter("FechaPrivacidadDatos", fechaPrivacidadDatos) :
                new ObjectParameter("FechaPrivacidadDatos", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCandidato", cveCandidatoParameter, passwordParameter, nombreParameter, apellidoParameter, confirmadoParameter, correoParameter, codigoConfirmacionParameter, telefonoParameter, nacionalidadParameter, rFCParameter, direccionParameter, nombreImagenParameter, fechaPrivacidadDatosParameter);
        }
    
        public virtual int UpdateEvaluacion(string cveEvaluacion, Nullable<short> calificacion, string cveAplicacion, string cveJuez)
        {
            var cveEvaluacionParameter = cveEvaluacion != null ?
                new ObjectParameter("cveEvaluacion", cveEvaluacion) :
                new ObjectParameter("cveEvaluacion", typeof(string));
    
            var calificacionParameter = calificacion.HasValue ?
                new ObjectParameter("Calificacion", calificacion) :
                new ObjectParameter("Calificacion", typeof(short));
    
            var cveAplicacionParameter = cveAplicacion != null ?
                new ObjectParameter("cveAplicacion", cveAplicacion) :
                new ObjectParameter("cveAplicacion", typeof(string));
    
            var cveJuezParameter = cveJuez != null ?
                new ObjectParameter("cveJuez", cveJuez) :
                new ObjectParameter("cveJuez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEvaluacion", cveEvaluacionParameter, calificacionParameter, cveAplicacionParameter, cveJuezParameter);
        }
    
        public virtual int UpdateJuez(string cveJuez, string password, string nombre, string apellido, string correo, string nombreImagen)
        {
            var cveJuezParameter = cveJuez != null ?
                new ObjectParameter("cveJuez", cveJuez) :
                new ObjectParameter("cveJuez", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var nombreImagenParameter = nombreImagen != null ?
                new ObjectParameter("NombreImagen", nombreImagen) :
                new ObjectParameter("NombreImagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateJuez", cveJuezParameter, passwordParameter, nombreParameter, apellidoParameter, correoParameter, nombreImagenParameter);
        }
    
        public virtual int UpdatePremio(string cvePremio, string nombre, string nombreImagen, string descripcion, Nullable<System.DateTime> fechaCreacion, string usuarioCreacion, Nullable<System.DateTime> fechaEdicion, string usuarioEdicion)
        {
            var cvePremioParameter = cvePremio != null ?
                new ObjectParameter("cvePremio", cvePremio) :
                new ObjectParameter("cvePremio", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var nombreImagenParameter = nombreImagen != null ?
                new ObjectParameter("NombreImagen", nombreImagen) :
                new ObjectParameter("NombreImagen", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            var fechaEdicionParameter = fechaEdicion.HasValue ?
                new ObjectParameter("FechaEdicion", fechaEdicion) :
                new ObjectParameter("FechaEdicion", typeof(System.DateTime));
    
            var usuarioEdicionParameter = usuarioEdicion != null ?
                new ObjectParameter("UsuarioEdicion", usuarioEdicion) :
                new ObjectParameter("UsuarioEdicion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePremio", cvePremioParameter, nombreParameter, nombreImagenParameter, descripcionParameter, fechaCreacionParameter, usuarioCreacionParameter, fechaEdicionParameter, usuarioEdicionParameter);
        }
    
        public virtual int UpdateConvocatoria(string cveConvocatoria, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string cvePremio, string tituloConvocatoria, Nullable<System.DateTime> fechaVeredicto, Nullable<System.DateTime> fechaCreacion, string usuarioCreacion, Nullable<System.DateTime> fechaEdicion, string usuarioEdicion)
        {
            var cveConvocatoriaParameter = cveConvocatoria != null ?
                new ObjectParameter("cveConvocatoria", cveConvocatoria) :
                new ObjectParameter("cveConvocatoria", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var cvePremioParameter = cvePremio != null ?
                new ObjectParameter("cvePremio", cvePremio) :
                new ObjectParameter("cvePremio", typeof(string));
    
            var tituloConvocatoriaParameter = tituloConvocatoria != null ?
                new ObjectParameter("TituloConvocatoria", tituloConvocatoria) :
                new ObjectParameter("TituloConvocatoria", typeof(string));
    
            var fechaVeredictoParameter = fechaVeredicto.HasValue ?
                new ObjectParameter("FechaVeredicto", fechaVeredicto) :
                new ObjectParameter("FechaVeredicto", typeof(System.DateTime));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            var fechaEdicionParameter = fechaEdicion.HasValue ?
                new ObjectParameter("FechaEdicion", fechaEdicion) :
                new ObjectParameter("FechaEdicion", typeof(System.DateTime));
    
            var usuarioEdicionParameter = usuarioEdicion != null ?
                new ObjectParameter("UsuarioEdicion", usuarioEdicion) :
                new ObjectParameter("UsuarioEdicion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateConvocatoria", cveConvocatoriaParameter, fechaInicioParameter, fechaFinParameter, cvePremioParameter, tituloConvocatoriaParameter, fechaVeredictoParameter, fechaCreacionParameter, usuarioCreacionParameter, fechaEdicionParameter, usuarioEdicionParameter);
        }
    
        public virtual ObjectResult<PI_SE_Configuracion> GetConfiguracion(string cveConfiguracion)
        {
            var cveConfiguracionParameter = cveConfiguracion != null ?
                new ObjectParameter("cveConfiguracion", cveConfiguracion) :
                new ObjectParameter("cveConfiguracion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_SE_Configuracion>("GetConfiguracion", cveConfiguracionParameter);
        }
    
        public virtual ObjectResult<PI_SE_Configuracion> GetConfiguracion(string cveConfiguracion, MergeOption mergeOption)
        {
            var cveConfiguracionParameter = cveConfiguracion != null ?
                new ObjectParameter("cveConfiguracion", cveConfiguracion) :
                new ObjectParameter("cveConfiguracion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PI_SE_Configuracion>("GetConfiguracion", mergeOption, cveConfiguracionParameter);
        }
    }
}
