//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiosInstitucionales.Entities.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wPremiosInstitucionalesdbEntities : DbContext
    {
        public wPremiosInstitucionalesdbEntities()
            : base("name=wPremiosInstitucionalesdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PI_BA_Aplicacion> PI_BA_Aplicacion { get; set; }
        public virtual DbSet<PI_BA_Candidato> PI_BA_Candidato { get; set; }
        public virtual DbSet<PI_BA_Categoria> PI_BA_Categoria { get; set; }
        public virtual DbSet<PI_BA_Convocatoria> PI_BA_Convocatoria { get; set; }
        public virtual DbSet<PI_BA_Evaluacion> PI_BA_Evaluacion { get; set; }
        public virtual DbSet<PI_BA_Forma> PI_BA_Forma { get; set; }
        public virtual DbSet<PI_BA_Juez> PI_BA_Juez { get; set; }
        public virtual DbSet<PI_BA_JuezPorCategoria> PI_BA_JuezPorCategoria { get; set; }
        public virtual DbSet<PI_BA_Pregunta> PI_BA_Pregunta { get; set; }
        public virtual DbSet<PI_BA_PreguntasPorForma> PI_BA_PreguntasPorForma { get; set; }
        public virtual DbSet<PI_BA_Premio> PI_BA_Premio { get; set; }
        public virtual DbSet<PI_BA_Respuesta> PI_BA_Respuesta { get; set; }
        public virtual DbSet<PI_SE_Administrador> PI_SE_Administrador { get; set; }
    }
}
